version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: food_wander
    depends_on:
      - db
      - redis
    networks:
      - foodWanderService

  db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: root
      POSRTGRES_PASSWORD: 123456
      POSTGRES_DB: food_wander
    ports:
      - "3306:3306"
    networks:
      - foodWanderService

networks:
  foodWanderService:


volumes:
  db_data: